name: nightwatch-testing-library
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    name: 'node ${{ matrix.node }} ${{matrix.browser}}  ${{ matrix.os }} '
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 10]
        browser: ["chrome:headless"]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - run: npm ci
      - uses: nanasess/setup-chromedriver@master
        # with:
          # Optional: do not specify to match Chrome's version
          #chromedriver-version: '77.0.3865.40'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - run: npm run validate
